### PR TITLE
Fix leaked decor view

### LINKED ISSUE #97: Dialog leaked window
E/WindowManager: android.view.WindowLeaked: Activity pub.devrel.easypermissions.AppSettingsDialogHolderActivity has leaked window DecorView@e08daea[] that was originally added here
                                                                at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
                                                                at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                at android.app.Dialog.show(Dialog.java:322)
                                                                at pub.devrel.easypermissions.AppSettingsDialog.showDialog(AppSettingsDialog.java:130)
                                                                at pub.devrel.easypermissions.AppSettingsDialogHolderActivity.onCreate(AppSettingsDialogHolderActivity.java:25)
                                                                at android.app.Activity.performCreate(Activity.java:6679)
                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Fixes #97

### CODE REVIEW

File: easypermissions/src/main/java/pub/devrel/easypermissions/AppSettingsDialogHolderActivity.java [hunk 1]
```diff
@@ -22,7 +25,13 @@ protected void onCreate(Bundle savedInstanceState) {
...
         dialog.setActivityOrFragment(this);
         dialog.setNegativeListener(this);
-        dialog.showDialog();
+        mDialog = dialog.showDialog();
+    }
+
+    @Override
+    protected void onDestroy() {
+        super.onDestroy();
+        mDialog.dismiss();
```
Comment (samtstern) [inline easypermissions/src/main/java/pub/devrel/easypermissions/AppSettingsDialogHolderActivity.java]: To be safe:

```
if (mDialog != null && mDialog.isShowing()) {
   mDialog.dismiss();
}
```

Comment (SUPERCILEX) [inline easypermissions/src/main/java/pub/devrel/easypermissions/AppSettingsDialogHolderActivity.java]: Yup, better be safe than sorry! 😄
